# See Makefile target `manifest` if testing config or deploying manually.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../infrastructure/org-codename-dev/config
- ../base
- ingress.yml
